# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(652, 388)
        self.lineEdit_FileName = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_FileName.setGeometry(QtCore.QRect(70, 30, 421, 31))
        self.lineEdit_FileName.setReadOnly(True)
        self.lineEdit_FileName.setObjectName("lineEdit_FileName")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 51, 16))
        self.label.setObjectName("label")
        self.pushButton_opn = QtWidgets.QPushButton(Dialog)
        self.pushButton_opn.setGeometry(QtCore.QRect(510, 30, 121, 28))
        self.pushButton_opn.setObjectName("pushButton_opn")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 80, 611, 221))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_gen = QtWidgets.QPushButton(Dialog)
        self.pushButton_gen.setGeometry(QtCore.QRect(80, 320, 93, 51))
        self.pushButton_gen.setObjectName("pushButton_gen")
        self.pushButton_cpy = QtWidgets.QPushButton(Dialog)
        self.pushButton_cpy.setGeometry(QtCore.QRect(450, 320, 93, 51))
        self.pushButton_cpy.setObjectName("pushButton_cpy")
        self.pushButton_cln = QtWidgets.QPushButton(Dialog)
        self.pushButton_cln.setGeometry(QtCore.QRect(270, 320, 93, 51))
        self.pushButton_cln.setObjectName("pushButton_cln")

        self.retranslateUi(Dialog)
        self.pushButton_cpy.clicked.connect(self.textBrowser.selectAll) # type: ignore
        self.pushButton_cpy.clicked.connect(self.textBrowser.copy) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hash Tool"))
        self.label.setText(_translate("Dialog", "File:"))
        self.pushButton_opn.setText(_translate("Dialog", "Open File..."))
        self.pushButton_opn.setShortcut(_translate("Dialog", "Ctrl+O"))
        self.pushButton_gen.setText(_translate("Dialog", "Generate\n"
"(Ctrl+G)"))
        self.pushButton_gen.setShortcut(_translate("Dialog", "Ctrl+G"))
        self.pushButton_cpy.setText(_translate("Dialog", "Copy All\n"
"(Alt+C)"))
        self.pushButton_cpy.setShortcut(_translate("Dialog", "Alt+C"))
        self.pushButton_cln.setText(_translate("Dialog", "Clean\n"
"(Ctrl+L)"))
        self.pushButton_cln.setShortcut(_translate("Dialog", "Ctrl+L"))
